name: workflowCI

on:
  push:
    branches:
      -main
  pull:
    branches:
      -main

defaults:
  run:
    working-directory: frontend/gmusic/

jobs:
  job-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      -name: Obtendo nodejs 16
       with:
        node-version: 16.x

      -name: Instalando dependencias
       run: npm install
      
      -name: Testando
       run: npm run test -- --coverage
       env:
        CI: true