name: workflowCD-PROD

on:
  pull_request:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  job-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Setando conexao SSH do Google Cloud
        run: |
          mkdir -p ~/.ssh/	
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GOOGLE_CLOUD_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_IP }}
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtendo nodejs 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
        
      - name: Instalando dependencias e angular
        run: |
          cd frontend/gmusic/
          npm install
          npm cache clean --force
          npm cache verify
          npm install -g @angular/cli
          ng config -g cli.warnings.versionMismatch false
          ng analytics off
      
      - name: Fazendo Build PROD
        run: |
          cd frontend/gmusic/
          ng build
      
      - name: Fazendo Deploy no ambiente de PROD(master)
        run: |
          ssh google-cloud 'sudo systemctl stop nginx'
          ssh google-cloud 'sudo rm -fr /usr/share/nginx/prod/*'
          ssh google-cloud 'sudo rm -fr /home/github/prod/*'
          cd frontend/gmusic/dist
          scp -r gmusic google-cloud:/home/github/prod/
          ssh google-cloud 'sudo cp -r /home/github/prod/gmusic/* /usr/share/nginx/prod/'
          ssh google-cloud 'sudo systemctl start nginx'

      - name: Uso do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
    
