name: workflowCICD-DEV

on:
  push:
    branches:
      - release
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  job-CI-DEV:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Uso do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARTOKEN }}

  job-CD-DEV:
    needs: job-CI-DEV
    runs-on: ubuntu-latest
    steps:
      - name: Setando conexao SSH do Google Cloud
        run: |
          mkdir -p ~/.ssh/	
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GOOGLE_CLOUD_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_IP }}
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtendo nodejs 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
        
      - name: Instalando dependencias e angular
        run: |
          cd frontend/gmusic/
          npm install
          npm cache clean --force
          npm cache verify
          npm install -g @angular/cli
          ng config -g cli.warnings.versionMismatch false
          ng analytics off
          
      - name: Fazendo alteracao para DEV
        run: |
          cd frontend/gmusic/src/app/components/login/
          agora="$(TZ=America/Sao_Paulo date -d now +'%c')"
          sed -i '1 i\Ambiente DEV - '"$agora" login.component.html
      
      - name: Fazendo Build DEV
        run: |
          cd frontend/gmusic/
          ng build
      
      - name: Fazendo Deploy no ambiente de DEV(release)
        run: |
          ssh google-cloud 'sudo systemctl stop nginx'
          ssh google-cloud 'sudo rm -fr /usr/share/nginx/dev/*'
          ssh google-cloud 'sudo rm -fr /home/github/dev/*'
          cd frontend/gmusic/dist
          scp -r gmusic google-cloud:/home/github/dev/
          ssh google-cloud 'sudo cp -r /home/github/dev/gmusic/* /usr/share/nginx/dev/'
          ssh google-cloud 'sudo systemctl start nginx'
          
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'frontend/gmusic/dist/gmusic'


      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
