name: workflowCD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
  workflow_dispatch:
  
defaults:
  run:
    working-directory: frontend/gmusic/

jobs:
  job-CD:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: dchat
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASS }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Teste
      run: |
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
    
