name: workflowCICD-DEV

on:
  push:
    branches:
      - release
  
jobs:
  #build e deploy da aplicacao  
  job-CI-DEV:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtendo Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Obtendo nodejs 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
        
      - name: Instalando dependencias e angular
        run: |
          cd frontend/gmusic/
          npm install
          npm cache clean --force
          npm cache verify
          npm install -g @angular/cli
          ng config -g cli.warnings.versionMismatch false
          ng analytics off
          
      - name: Setando properties
        run: |
          cat > backend/go-crud-api/.env << EOF
          PORT=8080
          DB_URL=$DB_URL
          EOF
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          DB_URL: ${{ secrets.DBURL }}
          
      
      - name: Fazendo Build do Angular
        run: |
          cd frontend/gmusic/
          ng build
          
      - name: Fazendo Build do Go
        run: |
          cd backend/go-crud-api/
          go build
