name: workflowCI-DEV

on:
  pull_request:
    branches:
      - release
  workflow_dispatch:
  
defaults:
  run:
    working-directory: frontend/gmusic/

jobs:
  job-CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Obtendo nodejs 16
      uses: actions/setup-node@v3
      with: 
        node-version: 16.x

    - name: Instalando dependencias e angular
      run: |
          cd frontend/gmusic/
          npm install
          npm cache clean --force
          npm cache verify
          npm install -g @angular/cli
          ng config -g cli.warnings.versionMismatch false
          ng analytics off

    - name: Fazendo teste de build
      run: |
          cd frontend/gmusic/
          ng build
      
      env:
        CI: true
    
    - name: Uso do SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
    
