name: workflowCI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
defaults:
  run:
    working-directory: frontend/gmusic/

jobs:
  job-CI:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: dchat
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASS }}
        ports:
          - 33306:3306
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Usando Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        cache: maven

    - name: Checando teste e coverage
      run: |
        cd /home/runner/work/Crud-Spring-Angular/Crud-Spring-Angular/backend/api
        mvn -v
        mvn clean install

    - name: Obtendo nodejs 16
      uses: actions/setup-node@v3
      with: 
        node-version: 16.x

    - name: Instalando dependencias
      run: npm install

    - name: Testando
    #pulando teste npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      run: echo "teste"
      env:
        CI: true
    
    - name: Uso do SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
    
